
vim.keymap.set('t', '<Esc>', '<c-\\><c-n><cr>')
-- local dap = require('dap')
-- dap.repl.toggle()
-- print(dap.session())
-- print(dap.status())
-- dap.run()
-- local widgets = require('dap.ui.widgets')
-- widgets.hover()
-- local my_sidebar = widgets.sidebar(widgets.scopes)
-- local my_sidebar = widgets.centered_float(widgets.sessions)
-- my_sidebar.open()
